# Generated by Django 3.0.2 on 2020-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Условие')),
                ('short_answer', models.CharField(max_length=200, verbose_name='Ответ (для автоматической проверки)')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('hint', models.TextField(verbose_name='Подсказка')),
            ],
        ),
    ]
