# Generated by Django 3.0.2 on 2020-01-06 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_auto_20200106_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['date_assigned']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to=settings.AUTH_USER_MODEL, verbose_name='Кем задано'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateField(auto_now_add=True, verbose_name='Когда задано'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_deadline',
            field=models.DateField(blank=True, verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому задано'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', verbose_name='Задача'),
        ),
    ]
