# Generated by Django 3.0.2 on 2020-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20200106_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ответ (для автоматической проверки)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Решение'),
        ),
    ]
