# Generated by Django 3.0.7 on 2021-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20210517_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskorder',
            name='number',
            field=models.CharField(default=0, max_length=1000, verbose_name='номер PaperObject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paperassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(1, 'Тест с ответом ДА/НЕТ'), (2, 'Тест с выбором одного ответа'), (3, 'Тест с выбором нескольких ответов'), (0, 'Задача'), (4, 'Качественная задача')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='taskorder',
            name='order',
            field=models.IntegerField(default=0, verbose_name='номер объекта в листе'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
