# Generated by Django 3.0.2 on 2020-01-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20200110_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='problems.Topic', verbose_name='Предок')),
            ],
            options={
                'ordering': ['parent', 'order'],
            },
        ),
    ]
