# Generated by Django 3.0.7 on 2021-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20210517_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paperassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(2, 'Тест с выбором одного ответа'), (0, 'Задача'), (3, 'Тест с выбором нескольких ответов'), (4, 'Качественная задача'), (1, 'Тест с ответом ДА/НЕТ')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (0, '---'), (2, 'Нет')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (0, '---'), (2, 'Нет')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (0, '---'), (2, 'Нет')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.DeleteModel(
            name='TaskOrder',
        ),
    ]
