# Generated by Django 3.0.2 on 2020-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20200110_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(related_name='problems', to='problems.Topic', verbose_name='Темы'),
        ),
    ]
