# Generated by Django 3.0.7 on 2021-05-20 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0009_auto_20210520_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (1, 'Ожидает проверки'), (0, 'Решение не сдано'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papersassigner', to=settings.AUTH_USER_MODEL, verbose_name='Кем задано'),
        ),
        migrations.AlterField(
            model_name='paperassignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (1, 'Ожидает проверки'), (0, 'Решение не сдано'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'Задача'), (2, 'Тест с выбором одного ответа'), (4, 'Качественная задача'), (3, 'Тест с выбором нескольких ответов'), (1, 'Тест с ответом ДА/НЕТ')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (1, 'Ожидает проверки'), (0, 'Решение не сдано'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
