# Generated by Django 3.0.2 on 2020-01-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20200110_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='leaf',
            field=models.BooleanField(default=False, verbose_name='Конечная вершина (можно привязывать задачи)'),
        ),
    ]
