# Generated by Django 3.0.2 on 2020-01-11 04:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_topic_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=ckeditor.fields.RichTextField(verbose_name='Условие'),
        ),
    ]
