# Generated by Django 3.0.2 on 2020-01-11 04:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20200111_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Решение'),
        ),
    ]
