# Generated by Django 3.0.2 on 2020-01-11 05:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20200111_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Условие'),
        ),
    ]
