# Generated by Django 3.0.7 on 2021-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20210520_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='blocks',
            field=models.ManyToManyField(to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paperassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'Задача'), (4, 'Качественная задача'), (2, 'Тест с выбором одного ответа'), (1, 'Тест с ответом ДА/НЕТ'), (3, 'Тест с выбором нескольких ответов')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
