# Generated by Django 3.0.2 on 2020-01-11 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20200111_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer', models.CharField(blank=True, max_length=200, verbose_name='Ответ (для автоматической проверки)')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Решение')),
                ('submit_datetime', models.DateTimeField(verbose_name='Время и дата сдачи решения')),
                ('verdict', models.IntegerField(blank=True, choices=[(0, 'Неверное решение'), (1, 'Частично верное решение'), (2, 'Верное решение с недочетами'), (3, 'Верное решение')], verbose_name='Результат проверки')),
                ('teacher_comment', models.CharField(blank=True, max_length=2000, verbose_name='Комментарий учителя')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='problems.Assignment', verbose_name='Назначенная задача')),
            ],
        ),
    ]
