# Generated by Django 3.0.2 on 2020-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий учителя'),
        ),
    ]
