# Generated by Django 3.0.2 on 2020-01-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20200111_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Решение проверено'), (1, 'Решение не проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время и дата сдачи решения'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='verdict',
            field=models.IntegerField(choices=[(-1, 'Решение не проверено'), (0, 'Неверное решение'), (1, 'Частично верное решение'), (2, 'Верное решение с недочетами'), (3, 'Верное решение')], default=-1, verbose_name='Результат проверки'),
        ),
    ]
