# Generated by Django 3.0.2 on 2020-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_auto_20200111_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['status', 'date_deadline']},
        ),
        migrations.AddField(
            model_name='submit',
            name='answer_autoverdict',
            field=models.BooleanField(blank=True, null=True, verbose_name='Результат автоматической проверки ответа'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Решение не проверено'), (2, 'Решение проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
    ]
