# Generated by Django 3.0.2 on 2020-01-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_auto_20200111_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='problems.Source', verbose_name='Предок')),
                ('problem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
