# Generated by Django 3.0.2 on 2020-01-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='source',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problems.Source'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Решение не проверено'), (2, 'Решение проверено')], default=0, verbose_name='Статус'),
        ),
    ]
