# Generated by Django 3.0.2 on 2020-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20200112_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Решение проверено'), (0, 'Решение не сдано'), (1, 'Решение не проверено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
    ]
