# Generated by Django 3.0.2 on 2020-01-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_auto_20200112_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Решение проверено'), (0, 'Решение не сдано'), (1, 'Решение не проверено')], default=0, verbose_name='Статус'),
        ),
    ]
