# Generated by Django 3.0.2 on 2020-01-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_auto_20200112_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Решение не проверено'), (0, 'Решение не сдано'), (2, 'Решение проверено')], default=0, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
