# Generated by Django 3.0.2 on 2020-01-15 01:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_auto_20200112_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Решение проверено'), (1, 'Решение не проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='teacher_comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Комментарий учителя'),
        ),
    ]
