# Generated by Django 3.0.2 on 2020-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0030_auto_20200115_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Решение не проверено'), (2, 'Решение проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
    ]
