# Generated by Django 3.0.2 on 2020-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20200115_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(3, 'Несколько из нескольких'), (2, 'Один из нескольких'), (0, 'C открытым ответом'), (1, 'Да/нет')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (2, 'Решение проверено'), (1, 'Решение не проверено')], default=0, verbose_name='Статус'),
        ),
    ]
