# Generated by Django 3.0.2 on 2020-01-23 10:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0032_auto_20200123_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, 'C открытым ответом'), (2, 'Один из нескольких'), (3, 'Несколько из нескольких'), (1, 'Да/нет')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Решение не проверено'), (2, 'Решение проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'C открытым ответом'), (2, 'Один из нескольких'), (3, 'Несколько из нескольких'), (1, 'Да/нет')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вариант ответа')),
                ('right', models.IntegerField(choices=[(0, 'Да'), (1, 'Нет')], default=0, verbose_name='Верный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='problems.Problem', verbose_name='Варианты ответа')),
            ],
        ),
    ]
