# Generated by Django 3.0.2 on 2020-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_auto_20200123_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Решение проверено'), (0, 'Решение не сдано'), (1, 'Решение не проверено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(2, 'Один из нескольких'), (0, 'C открытым ответом'), (1, 'Да/нет'), (3, 'Несколько из нескольких')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='right',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Верный ответ'),
        ),
    ]
