# Generated by Django 3.0.2 on 2020-01-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0034_auto_20200123_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Решение не проверено'), (2, 'Решение проверено'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(3, 'Тест с выбором нескольких ответов'), (2, 'Тест с выбором одного ответа'), (0, 'Задача'), (4, 'Качественная задача'), (1, 'Тест с ответом ДА/НЕТ')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='problems.Problem', verbose_name='Задача'),
        ),
    ]
