# Generated by Django 3.0.2 on 2020-01-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0040_auto_20200126_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Проверено учителем'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(4, 'Качественная задача'), (3, 'Тест с выбором нескольких ответов'), (1, 'Тест с ответом ДА/НЕТ'), (2, 'Тест с выбором одного ответа'), (0, 'Задача')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Вариант ответа'),
        ),
    ]
