# Generated by Django 3.0.2 on 2020-01-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0043_auto_20200129_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(1, 'Тест с ответом ДА/НЕТ'), (3, 'Тест с выбором нескольких ответов'), (0, 'Задача'), (2, 'Тест с выбором одного ответа'), (4, 'Качественная задача')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=None, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.CreateModel(
            name='TestSetAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True, verbose_name='Когда задано')),
                ('date_deadline', models.DateField(blank=True, null=True, verbose_name='Сдать до')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testset_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Кем задано')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому задано')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.TestSet', verbose_name='Тест')),
            ],
            options={
                'ordering': ['date_deadline'],
            },
        ),
    ]
