# Generated by Django 3.0.2 on 2020-01-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0045_auto_20200129_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'Задача'), (1, 'Тест с ответом ДА/НЕТ'), (4, 'Качественная задача'), (2, 'Тест с выбором одного ответа'), (3, 'Тест с выбором нескольких ответов')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(blank=True, choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=None, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.CreateModel(
            name='TestSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesno_answer', models.IntegerField(choices=[(2, 'Нет'), (0, '---'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ')),
                ('multiplechoice_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Выбор ответов')),
                ('submit_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата сдачи решения')),
                ('answer_autoverdict', models.BooleanField(blank=True, null=True, verbose_name='Результат автоматической проверки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='problems.TestSetAssignment', verbose_name='Назначенный тест')),
            ],
        ),
    ]
