# Generated by Django 3.0.2 on 2020-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0047_auto_20200131_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (1, 'Ожидает проверки'), (0, 'Решение не сдано'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(2, 'Тест с выбором одного ответа'), (1, 'Тест с ответом ДА/НЕТ'), (0, 'Задача'), (3, 'Тест с выбором нескольких ответов'), (4, 'Качественная задача')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=None, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (1, 'Ожидает проверки'), (0, 'Решение не сдано'), (2, 'Проверено учителем')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
