# Generated by Django 3.0.2 on 2020-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0053_auto_20200316_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Проверено учителем'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(1, 'Тест с ответом ДА/НЕТ'), (2, 'Тест с выбором одного ответа'), (3, 'Тест с выбором нескольких ответов'), (4, 'Качественная задача'), (0, 'Задача')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(2, 'Проверено учителем'), (1, 'Ожидает проверки'), (3, 'Проверено автоматически'), (0, 'Решение не сдано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
