# Generated by Django 4.1 on 2022-08-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0057_auto_20200927_1253'),
    ]

    operations = [

        migrations.AddField(
            model_name='testsubmit',
            name='short_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ответ (для автоматической проверки)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (0, 'Решение не сдано'), (2, 'Проверено учителем'), (1, 'Ожидает проверки')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='groupteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'Задача'), (1, 'Тест с ответом ДА/НЕТ'), (5, 'Тест с открытым ответом'), (3, 'Тест с выбором нескольких ответов'), (4, 'Качественная задача'), (2, 'Тест с выбором одного ответа')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Проверено автоматически'), (0, 'Решение не сдано'), (2, 'Проверено учителем'), (1, 'Ожидает проверки')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(2, 'Нет'), (1, 'Да'), (0, '---')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
