# Generated by Django 3.0.7 on 2021-05-22 15:04

from django.db import migrations
from economics.settings import TOPIC_ROOT, TOPIC_UNALLOCATED

def assign_topic_parents(apps, schema_editor):
    print(end='\n (миграция может занять некоторое время) ')
    Problem, Topic = (apps.get_model('problems', model) for model in ('Problem', 'Topic'))
    problems = Problem.objects.all()

    problems_of_topics_new = {}
    topics = {topic['id']: topic for topic in Topic.objects.values()}
    topics_by_problem = {}

    for problem in problems:
        for topic in problem.topics.values():
            while topic['id'] != TOPIC_ROOT:
                topic = topics[topic['parent_id']]
                problems_of_topics_new.setdefault(topic['id'], set())
                if problem.id not in problems_of_topics_new[topic['id']]:
                    problem.topics.add(topic['id'])
                    problems_of_topics_new[topic['id']].add(problem.id)
        if problem.topics.count() == 1:  # только корневая тема, добавляем, что тема не указана
            problem.topics.add(TOPIC_UNALLOCATED)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0058_auto_20210522_1742'),
    ]

    operations = [
        migrations.RunPython(assign_topic_parents, atomic=True)
    ]
