# Generated by Django 4.1 on 2022-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0058_testset_assigned_by_testsubmit_short_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.IntegerField(choices=[(2, 'Тест с выбором одного ответа'), (0, 'Задача'), (3, 'Тест с выбором нескольких ответов'), (4, 'Качественная задача'), (5, 'Тест с открытым ответом'), (1, 'Тест с ответом ДА/НЕТ')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='yesno_answer',
            field=models.IntegerField(choices=[(0, '---'), (2, 'Нет'), (1, 'Да')], default=0, verbose_name='Ответ ДА/НЕТ'),
        ),
    ]
