# Generated by Django 3.1.4 on 2022-08-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0060_testset_assigned_by_alter_problem_problem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests_assigner', to='auth.user', verbose_name='Кем задано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsubmit',
            name='short_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ответ (для автоматической проверки)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='groupteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Решение не сдано'), (1, 'Ожидает проверки'), (2, 'Проверено учителем'), (3, 'Проверено автоматически')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='answer_autoverdict',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Результат автоматической проверки'),
        ),
    ]
